# Generated by Django 4.2.1 on 2023-05-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='name',
            field=models.CharField(blank=True, null=True, verbose_name=20),
        ),
    ]
