# Generated by Django 4.2.1 on 2023-06-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_share', '0002_alter_image_upload_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='num_images',
            field=models.IntegerField(default=0),
        ),
    ]
