# Generated by Django 4.2.1 on 2023-06-14 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_review_author_alter_film_release_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='film',
            name='release_date',
            field=models.DateField(default=datetime.date(2023, 6, 14)),
        ),
        migrations.AddField(
            model_name='film',
            name='producers',
            field=models.ManyToManyField(related_name='films', to='films.producer'),
        ),
    ]
