# Generated by Django 4.2.2 on 2023-06-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_room_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
