# Generated by Django 4.2.1 on 2023-06-03 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0011_alter_rental_return_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='size',
            new_name='vehicle',
        ),
    ]
