# Generated by Django 4.2.1 on 2023-05-31 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='gifs',
        ),
        migrations.AddField(
            model_name='gif',
            name='category',
            field=models.ManyToManyField(to='gifs.category'),
        ),
    ]
